package regenmerge

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarkerlessFilesWouldDropKeepsStandalonePackage(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "handpkg", "client.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package handpkg\n\nfunc Keep() string { return \"hand\" }\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"same-spec merge must keep a markerless standalone package")
}

func TestMarkerlessFilesWouldDropListsNovelOnlyOverwrite(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "client.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package client\n\nfunc HandReplaced() string { return \"mine\" }\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package client

func New() string { return "fresh" }
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"same-spec merge preserves a markerless replacement at a generated path")
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a markerless generated-path file must be listed")
}

func TestMarkerlessFilesWouldDropSkipsMarkedAndTodoScaffolds(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	markedRel := filepath.Join("internal", "cli", "old_generated.go")
	scaffoldRel := filepath.Join("internal", "cli", "calls_cost.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, markedRel), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func stale() {}
`), 0o644))
	scaffold := []byte(`// Novel command scaffold. Implement the RunE body; generate --force preserves this file.
package cli

func newCallsCostCmd() { _ = "TODO: implement novel feature" }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, scaffoldRel), scaffold, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, scaffoldRel), scaffold, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"stale generated files and unimplemented scaffolds are not confirmation targets")
}

func TestMarkerlessFilesWouldDropIgnoresFreshOnlyEmission(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "cli", "new_emission.go")
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package cli\n\nfunc NewEmission() {}\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"a file that exists only in fresh is not a snapshot delete")
}

func TestMarkerlessFilesWouldDropListsSameDeclBodyReplacement(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "client.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package client\n\nfunc New() string { return \"mine\" }\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package client

func New() string { return "fresh" }
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"same-spec merge preserves a markerless same-decl replacement")
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a same-decl hand-authored body must be listed")
}

func TestMarkerlessFilesWouldDropListsSameDeclBodyReplacementWhenFreshIsMarkerless(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "cliutil", "testenv", "testenv.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package testenv\n\nfunc Isolate() string { return \"hand\" }\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package testenv\n\nfunc Isolate() string { return \"fresh\" }\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"same-spec merge preserves a markerless same-decl replacement")
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a markerless same-decl hand-authored body must be listed")
}

func TestMarkerlessFilesWouldDropSkipsSpecDerivedTestFunctionLiterals(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "platform_rate_limit_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package client\n\nfunc platformRateLimitTestClient() string { return \"old-pp-cli\" }\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package client\n\nfunc platformRateLimitTestClient() string { return \"new-pp-cli\" }\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"spec-derived literals in a markerless generated test helper are not a hand-authored delete")
}

func TestMarkerlessFilesWouldDropListsHandEditedTestAssertions(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "items_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func TestItems(t *testing.T) {
	got := 3
	if got != 3 {
		t.Fatalf("got %d", got)
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func TestItems(t *testing.T) {
	got := 3
	if got != 5 {
		t.Fatalf("got %d", got)
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true}),
		"same-spec merge preserves a markerless hand-edited test")
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a same-decl hand-authored test assertion must be listed")
}

func TestMarkerlessFilesWouldDropListsHandEditedTestControlFlow(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "items_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func TestItems(t *testing.T) {
	t.Fatal("no")
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func TestItems(t *testing.T) {
	if true {
		t.Fatal("no")
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a same-decl hand-authored test control-flow edit must be listed")
}

func TestMarkerlessFilesWouldDropListsHandEditedTestReturn(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "items_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package client\n\nfunc helper() bool { return true }\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package client\n\nfunc helper() bool { return false }\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"NovelOnly overwrite of a same-decl hand-authored test return must be listed")
}

func TestMarkerlessFilesWouldDropListsHandEditedTestDespiteSpecLiteralRefresh(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "platform_rate_limit_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "old-pp-cli" }

func TestRateLimit(t *testing.T) {
	got := 3
	if got != 3 {
		t.Fatalf("got %d", got)
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "new-pp-cli" }

func TestRateLimit(t *testing.T) {
	got := 3
	if got != 5 {
		t.Fatalf("got %d", got)
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"spec-literal helper refresh must not hide a hand-authored test assertion")
}

func TestMarkerlessFilesWouldDropListsSpecNameSubstringInTestLiteral(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "platform_rate_limit_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "oldapi-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "cache-oldapi-snapshot" {
		t.Fatal(got)
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "newapi-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "cache-newapi-snapshot" {
		t.Fatal(got)
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"a spec-name substring inside a larger hand-authored literal is not identity refresh")
}

func TestMarkerlessFilesWouldDropListsEmbeddedCLIIdentityInTestLiteral(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "platform_rate_limit_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "oldapi-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "use oldapi-pp-cli --hand" {
		t.Fatal(got)
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "newapi-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "use newapi-pp-cli --hand" {
		t.Fatal(got)
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"an embedded name-pp-cli token inside a larger hand-authored literal is not identity refresh")
}

func TestMarkerlessFilesWouldDropListsExactIdentityLiteralInNonHelper(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "platform_rate_limit_test.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "old-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "old-pp-cli" {
		t.Fatal(got)
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package client

import "testing"

func platformRateLimitTestClient() string { return "new-pp-cli" }

func TestItems(t *testing.T) {
	if got := "x"; got != "new-pp-cli" {
		t.Fatal(got)
	}
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"an exact identity literal in a non-helper test function is not identity refresh")
}

func TestMarkerlessFilesWouldDropListsUnparseableSnapshot(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "client.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package client\n\nfunc Broken( {\n\treturn \"hand\"\n}\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package client\n\nfunc New() string { return \"fresh\" }\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, []string{filepath.ToSlash(rel)}, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"an unparseable markerless snapshot file cannot be proven safe to replace")
}

func TestMarkerlessFilesWouldDropSkipsGeneratorValueDrift(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "cliutil", "testenv", "testenv.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte("package testenv\n\nconst Module = \"old-pp-cli\"\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte("package testenv\n\nconst Module = \"new-pp-cli\"\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"spec-derived literal drift in a markerless generated file is not a hand-authored delete")
}

func TestMarkerlessFilesWouldDropSkipsIdenticalFreshCopy(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "store", "extras.go")
	body := []byte("package store\n\nfunc migrateExtras() {}\n")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), body, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), body, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Empty(t, MarkerlessFilesWouldDrop(snap, fresh, report, Options{Force: true, NovelOnly: true}),
		"identical markerless generated files are not a hand-authored delete")
}
